version: '3.7'
services:
  app:
    container_name: api-graphql-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - 'PORT=${APP_PORT}'
        - 'NODE_ENV=${NODE_ENV}'
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - '.:/home/node/app'
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - 8080:8080
    networks:
      - api-graphql-network
    command: 'npm run start:dev'
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: api-graphql-db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - './docker/volumes/dbdata:/var/lib/mysql'
    env_file:
      - ./docker/mysql/.env
    networks:
      - api-graphql-network
networks:
  api-graphql-network: null
